version: "3.8"

services:
  postgresql:
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    env_file:
      - .env.test

  celery-worker:
    env_file:
      - .env.test

  grafana:
    env_file:
      - .env.test
