version: "3.8"

services:
  postgresql:
    image: postgres:14-alpine
    env_file:
      - .env.shared
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: ./compose/celery/Dockerfile
    env_file:
      - .env.shared
    volumes:
      - .:/app
    depends_on:
      - redis

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    env_file:
      - .env.shared

volumes:
  postgres_data:
