[tool.poetry]
name = "bp2022-ap1"
version = "0.1.0"
description = ""
authors = [
    "Antony Kamp <antony.kamp@student.hpi.de>",
    "Max Lietze <max.lietze@student.hpi.de>",
    "Luke Ortlam <luke.ortlam@student.hpi.de>",
    "Anton Persitzky <anton.persitzky@student.hpi.de>",
    "Christian Raue <christian.raue@student.hpi.de>",
    "Lucas Reisener <lucas.reisener@student.hpi.de>"
]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
traci = "^1.16.0"
jsonschema = "^4.17.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
black = "^23.1.0"
isort = "^5.12.0"
pylint = "^2.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
