{
 "title": "Run based",
 "time": { "from": "2020-01-01T00:17:30.000Z", "to": "2020-01-01T04:20:30.000Z" },
 "templating": {
  "list": [
   { "name": "run_id", "label": "Run ID", "query": "get_all_run_ids" }
  ]
 },
 "panels": [
  { "title": "Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Verkehrsleistung akkumuliert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "get_verkehrsleistung_time_by_run_id:${run_id}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Verkehrsleistung momentan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "get_verkehrsleistung_momentarily_time_by_run_id:${run_id}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Kohlebedarf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "target": "get_coal_demand_by_run_id:${run_id}",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Scalar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Verkehrsmenge",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "target": "get_verkehrsmenge_by_run_id:${run_id}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Verkehrsleistung",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "target": "get_verkehrsleistung_by_run_id:${run_id}",
     "type": "table"
    }
   ]
  }
 ]
}