{
 "title": "Multi Config Based",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "config_ids", "label": "Config IDs", "query": "get_all_config_ids" }
  ]
 },
 "panels": [
  { "title": "Scalar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ankunftszeitfenster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "get_window_by_multi_config:${config_ids}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Abfahrtszeitfenster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "get_window_by_multi_config:${config_ids}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Verkehrsmenge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "target": "get_verkehrsmenge_by_multi_config:${config_ids}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Verkehrsleistung",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "target": "get_verkehrsleistung_by_multi_config:${config_ids}",
     "type": "table"
    }
   ]
  }
 ]
}