{
 "title": "Config based",
 "time": { "from": "2020-01-01T00:14:30.000Z", "to": "2020-01-01T04:19:30.000Z" },
 "templating": {
  "list": [
   { "name": "config_id", "label": "Config ID", "query": "get_all_config_ids" }
  ]
 },
 "panels": [
  { "title": "Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Verkehrsleistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "target": "get_verkehrsleistung_time_by_config_id:${config_id}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Kohlebedarf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "target": "get_coal_demand_by_config_id:${config_id}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Ankunfts- und Abfahrtszeitfenstergröße",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "get_window_size_time_by_config_id:${config_id}",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Scalar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Durschnittliche Abfahrts- und Ankunftszeitfenster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "get_window_by_config_id:${config_id}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Verkehrsleistung Zugkilometer pro Stunde",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "target": "get_verkehrsleistung_by_config_id:${config_id}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Ankunftszeitfenster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "get_window_all_by_config_id:${config_id}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Verkehrsmenge Zugkilometer",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "target": "get_verkehrsmenge_by_config_id:${config_id}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Abfahrtszeitfenster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "get_window_all_by_config_id:${config_id}",
     "type": "table"
    }
   ]
  },
  {
   "title": "Map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  }
 ]
}