# /component/fault-injecton/train-speed-fault
get:
  summary: Get ids of train-speed-fault configurations connected to a user.
  operationId: getTrainSpeedFaultConfigurationIds
  parameters:
    - in: query
      name: simulationId
      schema:
        type: string
        format: uuid
      description: Specify id of simulation if you only want to get the train-speed-fault configuration of a single simulation
  responses:
    "200":
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
              format: uuid
    "401":
      description: API token missing
    "404":
      description: Simulation not found
put:
  summary: Insert a new train-speed-fault component. Returns the id of the configuration object.
  operationId: createTrainSpeedFaultConfiguration
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../../schemas/FaultInjector/TrainSpeedFaultConfiguration.yaml"
  responses:
    "201":
      description: Successfully created new train-speed-fault configuration object
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                format: uuid
    "401":
      description: API token missing
